core/fit/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.contrib import admin
from rest_framework import routers
from portal.core.fit.views import api
 
from .views.base import IndexView

from .views import BioIleneRuskView
from .views import BioJamesDoranView
from .views import BioJimLeightonView
from .views import BioLaurenLeightonView
from .views import BioRenaKirklandView
from .views import BioShaneNiemeyerView

from .views import DimCognitiveView
from .views import DimEmotionalView
from .views import DimFinancialView
from .views import DimPhysicalView

from .views import AccountView
from .views import AssessmentView
from .views import IndividualSurveyView
from .views import DemographicView
from .views import WelcomeView
from .views import SaveAnswer
from .views import FitScore
from .views import FitButtonCheck
from .views import HomeView

from .views.dashboard import DashboardView

from .views.calendar import CalendarView
from .views.calendar import CalendarDetailsView
from .views.calendar import CalendarICS

from .views.library import LibraryDimensionView
from .views.library import LibraryResourceView

from .views.dreambuilder import DreamBuilderView
from .views.dreambuilder import DreamEnvironment
from .views.dreambuilder import DreamPurposeView
from .views.dreambuilder import DreamPrinciplesView
from .views.dreambuilder import SaveEnvironment
from .views.dreambuilder import UpdatePurpose
from .views.dreambuilder import SaveDefinedPrinciples
from .views.dreambuilder import SaveVisionView
from .views.dreambuilder import SavePurposeAnswers
from .views.dreambuilder import UpdatePrinciple
from .views.dreambuilder import DreamDefPrinciplesView
from .views.dreambuilder import DreamVisionView
from .views.dreambuilder import DreamReportView
from .views.dreambuilder import DreamStatementView
from .views.dreambuilder import SavePurposeStatement

from .views.planbuilder import PlanBuilder
from .views.planbuilder import PlanBuilderObjects
from .views.planbuilder import PlanBuilderGoals
from .views.planbuilder import PlanBuilderAgenda
from .views.planbuilder import PlanObjects
from .views.planbuilder import AddObjective
from .views.planbuilder import RemoveObjective
from .views.planbuilder import LoadGoals
from .views.planbuilder import GetDimension
from .views.planbuilder import GetSubCategory
from .views.planbuilder import LoadTasks
from .views.planbuilder import AddTask
from .views.planbuilder import RemoveTask
from .views.planbuilder import ClearTasks

from .views import UsersAnswers
from .views import AllSurveysAnswer


router = routers.DefaultRouter()
router.register(r'^users', api.UserViewSet)
router.register(r'^groups', api.GroupViewSet)
router.register(r'^dimensions', api.DimensionViewSet)
router.register(r'^subcategories', api.SubCategoryViewSet)
router.register(r'^objectives', api.ObjectiveViewSet)
router.register(r'^agendas', api.AgendaViewSet)
router.register(r'^plans', api.PlanViewSet)


urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),


    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    
    url(r'^about/$', TemplateView.as_view(template_name='core/fit/home/about.html'), name='about'),
    
    url(r'^bios/ilene_rusk', BioIleneRuskView.as_view(), name='bio_ilene_rusk'),
    url(r'^bios/Ilene_Rusk', BioIleneRuskView.as_view(), name='bio_ilene_rusk'),
    url(r'^bios/james_doran', BioJamesDoranView.as_view(), name='bio_james_doran'),
    url(r'^bios/James_Doran', BioJamesDoranView.as_view(), name='bio_james_doran'),
    url(r'^bios/jim_leighton', BioJimLeightonView.as_view(), name='bio_jim_leighton'),
    url(r'^bios/Jim_Leighton', BioJimLeightonView.as_view(), name='bio_jim_leighton'),
    url(r'^bios/lauren_leighton', BioLaurenLeightonView.as_view(), name='bio_lauren_leighton'),
    url(r'^bios/rena_kirkland', BioRenaKirklandView.as_view(), name='bio_rena_kirkland'),
    url(r'^bios/Rena_Kirkland', BioRenaKirklandView.as_view(), name='bio_rena_kirkland'),
    url(r'^bios/shane_niemeyer', BioShaneNiemeyerView.as_view(), name='bio_shane_niemeyer'),
    url(r'^bios/Shane_Niemeyer', BioShaneNiemeyerView.as_view(), name='bio_shane_niemeyer'),

    url(r'^bios/', IndexView.as_view(), name='coach_bio'),
    
    url(r'^[Cc]ognitive', DimCognitiveView.as_view(), name='cognitive'),
    url(r'^[Ee]motional', DimEmotionalView.as_view(), name='emotional'),
    url(r'^[Ff]inancial', DimFinancialView.as_view(), name='financial'),
    url(r'^[Pp]hysical', DimPhysicalView.as_view(), name='physical'),
    
    url(r'^plan-builder/$', PlanBuilder.as_view(), name='plan_builder'),
    url(r'^plan-builder/objects/$', PlanBuilderObjects.as_view(), name='planbuilder_objects'),
    url(r'^plan/builder/objects/$', PlanBuilderObjects.as_view(), name='plan_builder_objects'),
    url(r'^plan/goals/$', PlanBuilderGoals.as_view(), name='plan_builder_goals'),
    url(r'^plan/agenda/$', PlanBuilderAgenda.as_view(), name='plan_builder_agenda'),
    url(r'^plan/objects/$', PlanObjects.as_view(), name='plan_objects'),
    url(r'^plan/AddPlanBuilderObject/$', AddObjective.as_view(), name='plan_create'),
    url(r'^plan/RemovePlanBuilderObject/$', RemoveObjective.as_view(), name='plan_remove'),
    url(r'^plan/LoadGoals/$', LoadGoals.as_view(), name='plan_load_goals'),
    url(r'^plan/GetDimension/$', GetDimension.as_view(), name='plan_get_dimension'),
    url(r'^plan/GetSubCategory/$', GetSubCategory.as_view(), name='plan_get_sub_category'),
    url(r'^plan/load-tasks/$', LoadTasks.as_view(), name='plan_load_Tasks'),
    url(r'^plan/add-task/$', AddTask.as_view(), name='plan_add_task'),
    url(r'^plan/remove-task/$', RemoveTask.as_view(), name='plan_remove_task'),
    url(r'^plan/clear-tasks/$', ClearTasks.as_view(), name='plan_clear_tasks'),
    
    url(r'^dream-builder/$', DreamBuilderView.as_view(), name='dream_builder'),
    url(r'^dream-builder/environment$', DreamEnvironment.as_view(), name='dreambuilder_environment'),
    url(r'^dream-builder/SaveEnvironment$', SaveEnvironment.as_view(), name='SaveEnviroment'),
    url(r'^dream-builder/purpose/$', DreamPurposeView.as_view(), name='dreambuilder_purpose'),

    url(r'^dream-builder/UpdatePurpose/$', UpdatePurpose.as_view(), name='dreambuilder_update'),
    
    url(r'^dreambuilder/UpdatePrinciple/$', UpdatePrinciple.as_view(), name='dreambuilder_updateprinciple'),
    
    url(r'^dream-builder/purpose/SavePurposeAnswers/$', SavePurposeAnswers.as_view(), name='SavePurposeAnswers'),
    url(r'^dream-builder/principles$', DreamPrinciplesView.as_view(), name='dreambuilder_principles'),
    url(r'^dream-builder/defineprinciples$', DreamDefPrinciplesView.as_view(), name='dreambuilder_defineprinciples'),
    
    url(r'^dream-builder/SaveDefinedPrinciples/$', SaveDefinedPrinciples.as_view(), name='SaveDefinedPrinciples'),
    url(r'^dream-builder/vision/$', DreamVisionView.as_view(), name='dreambuilder_vision'),
    
    url(r'^dream-builder/statement/$', DreamStatementView.as_view(), name='dreambuilder_statement'),
    
    url(r'^dream-builder/statement/SavePurposeStatement/$', SavePurposeStatement.as_view(), name='SavePurposeStatement'),
    
    url(r'^dream-builder/vision/SaveVision/$', SaveVisionView.as_view(), name='dreambuilder_savevision'),
    
    url(r'^dream-builder/report/$', DreamReportView.as_view(), name='dreambuilder_report'),
    
    url(r'^library/$', TemplateView.as_view(template_name='core/fit/library/index.html'), name='library'),
    url(r'^library/dimension/(?P<dimension_id>[-\w]+)/$', LibraryDimensionView.as_view(), name='library_dimension'),
    url(r'^library/resource/(?P<resource_id>[-\w]+)/$', LibraryResourceView.as_view(), name='library_resource'),

    url(r'^calendar/export/(?P<id>[-\w]+)/$', CalendarICS.as_view(), name="calendar_export"),
    
    url(r'^calendar/details/(?P<id>[-\w]+)/$', CalendarDetailsView.as_view(), name='calendar_details'),
    
    url(r'^calendar/$', CalendarView.as_view(), name='calendar'),
    
    url(r'^upgrade/$', IndexView.as_view(template_name='core/fit/dashboard.html'), name='upgrade'),
    
    url(r'^dashboard/$', DashboardView.as_view(), name='dashboard'),

    url(r'^demo/$', TemplateView.as_view(template_name='core/fit/demo.html'), name='demo'),
    url(r'^demo_p1/$', TemplateView.as_view(template_name='core/fit/demo_p1.html'), name='demo_p1'),
    url(r'^demo_p2/$', TemplateView.as_view(template_name='core/fit/demo_p2.html'), name='demo_p2'),
    url(r'^demo_p3/$', TemplateView.as_view(template_name='core/fit/demo_p3.html'), name='demo_p3'),
    url(r'^demo_p4/$', TemplateView.as_view(template_name='core/fit/demo_p4.html'), name='demo_p4'),
    url(r'^demo_p5/$', TemplateView.as_view(template_name='core/fit/demo_p5.html'), name='demo_p5'),
    url(r'^demo_p6/$', TemplateView.as_view(template_name='core/fit/demo_p6.html'), name='demo_p6'),

    url(r'^privacy_policy/$', TemplateView.as_view(template_name='core/fit/privacy_policy.html'), name='privacy_policy'),
    url(r'^termsofservice/$', TemplateView.as_view(template_name='core/fit/termsofservice.html'), name='termsofservice'),


    url(r'^history/$', DashboardView.as_view(), name='history'),
    
    url(r'^secure/account/$', AccountView.as_view(template_name='core/fit/secure/account.html'), name='account'),
    
    url(r'^secure/GetAllSurveysAnswer/$', AllSurveysAnswer.as_view(), name='secure_GetAllSurverysAnwser'),
    url(r'^secure/GetUsersAnwsers/$', UsersAnswers.as_view(), name='answers'),
    url(r'^secure/SaveFitScore/$', FitScore.as_view(), name='score'),
    
    url(r'^assessment/$', AssessmentView.as_view(template_name='core/fit/survey_update.html'), name='assessment'),  # New assesment
    
    url(r'^survey/answer/$', SaveAnswer.as_view(), name='survey_answer'),
    url(r'^survey/assessment/$', AssessmentView.as_view(), name='survey_assessment'),  # Continue assesment

urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from django.contrib import admin

import portal.views
import portal.core.fit
from portal.core.fit.views import logout

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('fit:index'))),
    url(r"^home/", RedirectView.as_view(url=reverse_lazy('fit:index')), name='home'),
    #url(r"^account/logout", RedirectView.as_view(url=reverse_lazy('logout'))),
    url(r"^f2/", include("portal.core.fit.urls", namespace='fit')),
    url(r'^logout/$', logout, name='logout'),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/signup/$", portal.views.SignupView.as_view(), name="account_signup"),
    url(r"^account/", include("account.urls")),
    url(r"^account/social/accounts/$", TemplateView.as_view(template_name="account/social.html"), name="account_social_accounts"),
    url(r"^account/social/", include("social.apps.django_app.urls", namespace="social")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/fit/models/answers.py
from django.db import models
from django.conf import settings


class Answer(models.Model):
    
    survey = models.ForeignKey('Survey')
    question = models.ForeignKey('Question')
    value = models.IntegerField(default=1, help_text="Range: [1-6]")

core/fit/models/calendars.py
from django.db import models
from django.conf import settings


class Calendar(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    start_date = models.DateField()
    end_date = models.DateField()


class Goal(models.Model):
    
    content = models.TextField()
    subcategory = models.ForeignKey('SubCategory') 


class Task(models.Model):
    
    content = models.TextField()
    goal = models.ForeignKey('Goal')


class Plan(models.Model):
    
    content = TextField(blank=True)
    schedule = models.TextField(help_text='ISO 8601 repeating interval notation')

core/fit/models/demographics.py
from django.db import models
from django.contrib import admin

# TODO: modern / international fields

class Demographic(models.Model):

    first_name = models.TextField()
    last_name = models.TextField()
    email = models.TextField()
    gender = models.TextField()
    marital_status = models.TextField() 
    date_of_birth = models.DateField()
    address_line1 = models.TextField()
    address_line2 = models.TextField() 
    state =  models.TextField()
    postal_code = models.TextField()
    phone = models.TextField()
    city = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)


admin.site.register(Demographic)

core/fit/models/dimensions.py
from django.db import models
from django.contrib import admin
from portal.core.fit.utils import ChoiceEnum


class DimensionId(ChoiceEnum):
    Cognitive = 1
    Emotional = 2
    Physical = 3
    Financial = 4


class Dimension(models.Model):

    id = models.IntegerField(primary_key=True, choices=DimensionId.choices())    
    name = models.TextField()
    divisor = models.IntegerField(default=5)
    description = models.TextField(blank=True)
    
    def __str__(self):
        return "%i: %s" % (self.id, self.name)


class SubCategory(models.Model):
    
    name = models.TextField()
    dimension = models.ForeignKey('Dimension')
    multiplier = models.IntegerField(default=5)
    
    def __str__(self):
        return "%02d: %s" % (self.id, self.name)


admin.site.register(Dimension)
admin.site.register(SubCategory)

core/fit/models/dream_builder_sessions.py
from django.db import models
from django.conf import settings


class DreamBuilderSession(models.Model):

    sequence_state = models.IntegerField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

core/fit/models/fit_scores.py
from django.db import models


class FitScore(models.Model):
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int SubCategoryId { get; set; }
        public decimal Score { get; set; }
        public int SurveyId { get; set; }
        public decimal Balance { get; set; }
        public decimal CognitiveFit { get; set; }
        public decimal CognitiveBal { get; set; }
        public decimal EmotionalFit { get; set; }
        public decimal EmotionalBal { get; set; }
        public decimal PhysicalFit { get; set; }
        public decimal PhysicalBal { get; set; }
        public decimal FinancialFit { get; set; }
        public decimal FinancialBal { get; set; }
        public DateTime CreateDate { get; set; }
    }

core/fit/models/fit_subscores.py
from django.db import models


public class FitSubScore(models.Model):
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public decimal Score { get; set; }
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public int FitScoreId { get; set; }
    }

core/fit/models/versions.py
public class Version:IEntity
    {
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public int VersionNumber { get; set; }
        public int UserId { get; set; }
        public DateTime CreateDate { get; set; }
        public string QuestionContent { get; set; }
    }

core/fit/views/api.py
from rest_framework import viewsets
from rest_framework.decorators import detail_route
from rest_framework.response import Response
from django.contrib.auth.models import User, Group
from portal.core.fit.models import Goal, Task, Progress
from portal.core.fit.models import Agenda, Objective, Plan
from portal.core.fit.models import Dimension, SubCategory
from portal.core.fit.permissions import IsAdminOrIsSelf
from portal.core.fit.serializers import *


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer


class DimensionViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Dimension.objects.all()
    serializer_class = DimensionSerializer


class SubCategoryViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = SubCategory.objects.all()
    serializer_class = SubCategorySerializer


class AgendaViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Agenda.objects.all()
    serializer_class = AgendaSerializer


class ObjectiveViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Objective.objects.all()
    serializer_class = ObjectiveSerializer
    
    
class PlanViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Plan.objects.all()
    serializer_class = PlanSerializer
    
    @detail_route(methods=['post'], permission_classes=[IsAdminOrIsSelf])
    def schedule(self, request, pk=None):
        plan = Plan.objects.get(pk=pk)
        plan.start = request.data['startsAt']
        plan.end = request.data['endsAt']
        plan.save()
        return Response({"ok":True})

core/fit/templates/core/fit/planbuilder/planbuilder_agenda2.html
{% load staticfiles %}
<!DOCTYPE html>
<html ng-app="mwl.calendar.docs">
  <head>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.1/moment.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/interact.js/1.2.4/interact.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-animate.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/2.0.0/ui-bootstrap-tpls.min.js"></script>
    <script src="//cdn.rawgit.com/jkbrzt/rrule/v2.1.0/lib/rrule.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular-bootstrap-colorpicker/3.0.25/js/bootstrap-colorpicker-module.min.js"></script>
    <script src="//mattlewis92.github.io/angular-bootstrap-calendar/dist/js/angular-bootstrap-calendar-tpls.min.js"></script>
    <script src="{% static 'js/cal-example.js' %}"></script>
    <script src="{% static 'js/cal-helpers.js' %}"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="//cdnjs.cloudflare.com/ajax/libs/angular-bootstrap-colorpicker/3.0.25/css/colorpicker.min.css" rel="stylesheet">
    <link href="//mattlewis92.github.io/angular-bootstrap-calendar/dist/css/angular-bootstrap-calendar.min.css" rel="stylesheet">
    
    <!-- Tasks  -->
    
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/headers/header-default.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/pages/page_about.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/theme-colors/default.css' %}" id="style_color">
    <link rel="stylesheet" href="{% static 'assets/css/theme-skins/dark.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/layouts/white_layout.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/headers/Custom_Header.css' %}" />
  </head>
  <body>

<!--=== Header ===-->
<div class="header">
    <div class="container padding-right-0 padding-left-0">
        <div class="col-xs-4 col-md-3">
            <a class="logo" href="{% url 'fit:dashboard' %}">
                <img class="secureAdminLogo" src="{% static 'assets/img/icons/dimension-icons/FIT-logo-sm.png' %}" />
            </a>
        </div>
        <div class="col-xs-8 col-md-9">
            <input type="text" class="search-bar form-control" placeholder="Search" ng-keyup="checkSearch($event)" ng-model="keyword" />
            <button onclick="hamburgerToggle(event)" class="hamburgerSecure">&#9776;</button>
            <!-- End Toggle -->
        </div>
    </div><!--/end container-->
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="container hamburgerMenuWrapper">
        <div id="secureHamDropdown" class="hamburgerContent">
            <a href="/secure/IndividualDashboard">Dashboard</a>
            <a href="/secure/IndividualSurvey">FIT Assessment</a>
            <a href="/secure/MySurveys">My History</a>
            <a href="/secure/account">My Account</a>
            <a href="{{takeFitLink}}">{{takeFitText}}</a>
            <a href="/home/logout">Log Out</a>
        </div>
    </div>
    <!--/navbar-collapse-->
</div>

{% verbatim %}
<div ng-controller="KitchenSinkCtrl as vm" class="container content">

    <div class="col-xs-12 col-md-6 col-md-offset-3" style="margin-bottom: 20px">
        <a class="col-xs-3" href="#">
            <div ng-click="filterGraph($event, 'cognitive')" class="icon-cognitive"></div>
        </a>
        <a class="col-xs-3 " href="#">
            <div ng-click="filterGraph($event , 'emotional')" class="icon-emotional"></div>
        </a>
        <a class="col-xs-3 " href="#">
            <div ng-click="filterGraph($event, 'physical')" class="icon-physical"></div>
        </a>
        <a class="col-xs-3 " href="#">
            <div ng-click="filterGraph($event, 'financial')" class="icon-financial"></div>
        </a>
    </div>
    <div class="col-md-10 col-md-offset-1 text-center">
        <div class="PB-horizontal-line"></div>
    </div>
    <div class="clearfix"></div>
  <h2 class="text-center">{{ vm.calendarTitle }}</h2>
   
  <br/>

  <h3 id="event-editor">
    <button
      class="btn btn-default pull-right"
      ng-click="vm.addEvent()">
      Add New
    </button>
    <div class="clearfix"></div>
  </h3>


    <div class="col-md-12" style="border: 1px solid #ccc; background-color: #fff; margin-bottom: 10px;" ng-repeat="event in vm.events track by $index">
        <div class="col-sm-6 margin-top-20">
            <table>
                <tr>
                    <td>
                        <div class="text-center" style="border-right: 1px solid #ddd;">
                            <div class="icon-Cognitive"></div>
                            <span style="font-size: 11px;">Cognitive</span>
                        </div>
                    </td>
                    <td>
                        <h4 class="text-bold" style="padding-left: 20px;">SubCategory Name</h4>
                        <h5 class="text-bold" style="padding-left: 20px;">Goal Text</h5>
                        <p style="margin-left: 1.25em;">This is some task text that should long enough</p>
                    </td>
                </tr>
            </table>
        </div>
    
        <div class="col-sm-6 margin-top-20">
            <div class="row">
                <div class="col-sm-6">
                    <p class="input-group" style="max-width: 250px">
                        <input
                          type="text"
                          class="form-control"
                          readonly
                          uib-datepicker-popup="dd MMMM yyyy"
                          ng-model="event.startsAt"
                          is-open="event.startOpen"
                          close-text="Close" >
                        <span class="input-group-btn">
                          <button
                            type="button"
                            class="btn btn-default"
                            ng-click="vm.toggle($event, 'startOpen', event)">
                            <i class="glyphicon glyphicon-calendar"></i>
                          </button>
                        </span>
                      </p>
                      <div
                        uib-timepicker
                        ng-model="event.startsAt"
                        hour-step="1"
                        minute-step="15"
                        show-meridian="true">
                      </div>
                  </div>
                  
                  <div lass="col-sm-3">
                  <p class="input-group" style="max-width: 250px">
                            <input
                              type="text"
                              class="form-control"
                              readonly
                              uib-datepicker-popup="dd MMMM yyyy"
                              ng-model="event.endsAt"
                              is-open="event.endOpen"
                              close-text="Close">
                            <span class="input-group-btn">
                              <button
                                type="button"
                                class="btn btn-default"
                                ng-click="vm.toggle($event, 'endOpen', event)">
                                <i class="glyphicon glyphicon-calendar"></i>
                              </button>
                            </span>
                          </p>
                      <div
                        uib-timepicker
                        ng-model="event.startsAt"
                        hour-step="1"
                        minute-step="15"
                        show-meridian="true">
                      </div>
                  </div>
              </div>
        </div>
    </div>
    
</div>

  </body>
{% endverbatim %}
</html>

core/fit/templates/core/fit/planbuilder/planbuilder_header.html
{% load staticfiles %}
<!--=== Header ===-->
<div class="header" ng-controller="TakeFitCtrl">
    <div class="container padding-right-0 padding-left-0">
        <div class="col-xs-4 col-md-3">
            <a class="logo" href="{% url 'fit:dashboard' %}">
                <img class="secureAdminLogo" src="{% static 'assets/img/icons/dimension-icons/FIT-logo-sm.png' %}" />
            </a>
        </div>

        <div class="col-xs-8 col-md-9">
            <input type="text" class="search-bar form-control" placeholder="Search" ng-keyup="checkSearch($event)" ng-model="keyword" />
            <button onclick="hamburgerToggle(event)" class="hamburgerSecure">&#9776;</button>
            <!-- End Toggle -->
        </div>
    </div><!--/end container-->
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="container hamburgerMenuWrapper">
        <div id="secureHamDropdown" class="hamburgerContent">
            <a href="/secure/IndividualDashboard">Dashboard</a>
            <a href="/secure/IndividualSurvey">FIT Assessment</a>
            <a href="/secure/MySurveys">My History</a>
            <a href="/secure/account">My Account</a>
            <a href="{{takeFitLink}}">{{takeFitText}}</a>
            <a href="/home/logout">Log Out</a>
        </div>
    </div>
    <!--/navbar-collapse-->
</div>
<script>


    fitApp.factory('TakeFitfactory', function ($http) {
        return {

            getFItButtonData: function (callback) {
                var url = "{% url 'fit:survey_check' %}";
                
                $http({ method: 'GET', url: url, headers: { 'Content-Type': 'application/json' } }).
                    success(function (data, status, headers, config) {
                        callback(data);

                    }).error(function (data, status, headers, config) {

                    });
            },
        }
    });

    fitApp.controller('TakeFitCtrl', function ($scope, TakeFitfactory) {

        $scope.takeFitLink = "/secure/NewSurvey";
        $scope.takeFitText = "Take FIT Assessment";
        $scope.keyword = "";

        TakeFitfactory.getFItButtonData(function (response) {
            data = response;

            $scope.takeFitLink = data.link;
            $scope.takeFitText = data.text;
        })

        $scope.checkSearch = function (event) {
            if (event.keyCode == 13) {
                window.location = "/f2/search/?q=" + $scope.keyword;
            }
        }
    }); 
</script>
<!--=== End Header ===-->